INSERT INTO Bancos ([Nome]) VALUES ('Banco Bankpar S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco da Amazônia S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco do Nordeste do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Standard de Investimentos S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('BANESTES S.A. Banco do Estado do Espírito Santo')
INSERT INTO Bancos ([Nome]) VALUES ('Banco de Pernambuco S.A. - BANDEPE')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Alfa S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Banerj S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Beg S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Santander (Brasil) S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bradesco BBI S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco do Estado do Pará S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cargill S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco do Estado do Rio Grande do Sul S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BVA S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Opportunity S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco do Estado de Sergipe S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Hipercard Banco Múltiplo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Ibi S.A. Banco Múltiplo')
INSERT INTO Bancos ([Nome]) VALUES ('Goldman Sachs do Brasil Banco Múltiplo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bracce S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('BPN Brasil Banco Múltiplo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('BRB - Banco de Brasília S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Rural Mais S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('BB Banco Popular do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco J. Safra S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('BES Investimento do Brasil S.A.-Banco de Investimento')
INSERT INTO Bancos ([Nome]) VALUES ('Banco JBS S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Concórdia Banco S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Topázio S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco da China Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BM&F de Serviços de Liquidação e Custódia S.A')
INSERT INTO Bancos ([Nome]) VALUES ('Caixa Econômica Federal')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BBM S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Western Union do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Itaú BBA S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bradesco Cartões S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BTG Pactual S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Dibens S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Comercial e de Investimento Sudameris S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco John Deere S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bonsucesso S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Credit Agricole Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Fibra S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Brascan S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cruzeiro do Sul S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Unicard Banco Múltiplo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cifra S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bradesco S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco ABC Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Boavista Interatlântico S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Investcred Unibanco S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Schahin S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cacique S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Fator S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BMG S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Industrial e Comercial S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Itaú Unibanco S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Real S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Société Générale Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco WestLB do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco J. P. Morgan S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Mercantil do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Bradesco Financiamentos S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Finasa BMC S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('HSBC Bank Brasil S.A. - Banco Múltiplo')
INSERT INTO Bancos ([Nome]) VALUES ('UNIBANCO - União de Bancos Brasileiros S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Safra S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Rural S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco de Tokyo-Mitsubishi UFJ Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Sumitomo Mitsui Brasileiro S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Caixa Geral - Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Citibank S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco ItaúBank S.A')
INSERT INTO Bancos ([Nome]) VALUES ('Deutsche Bank S.A. - Banco Alemão')
INSERT INTO Bancos ([Nome]) VALUES ('JPMorgan Chase Bank')
INSERT INTO Bancos ([Nome]) VALUES ('ING Bank N.V.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Credit Suisse (Brasil) S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Luso Brasileiro S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Industrial do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco VR S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Paulista S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Guanabara S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Panamericano S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Ficsa S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Rendimento S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Triângulo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Sofisa S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Prosper S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Alvorada S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Pine S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Itaú Unibanco Holding S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Indusval S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Votorantim S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Daycoval S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banif-Banco Internacional do Funchal (Brasil)S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BGN S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Barclays S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Citibank S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Modal S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Rabobank International Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cooperativo Sicredi S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Simples S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Scotiabank Brasil S.A. Banco Múltiplo')
INSERT INTO Bancos ([Nome]) VALUES ('Banco BNP Paribas Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Bank of America Merrill Lynch Banco Múltiplo S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Cooperativo do Brasil S.A. - BANCOOB')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Fiat S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco de Lage Landen Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco GMAC S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Citicard S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Itaucred Financiamentos S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco IBM S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Volkswagen S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Rodobens S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Ford S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco CNH Capital S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Toyota do Brasil S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Honda S.A.')
INSERT INTO Bancos ([Nome]) VALUES ('Banco Volvo (Brasil) S.A.')