INSERT INTO Funcaos ([Nome]) VALUES ('Abordagem')
INSERT INTO Funcaos ([Nome]) VALUES ('Administrativo')
INSERT INTO Funcaos ([Nome]) VALUES ('Atendente')
INSERT INTO Funcaos ([Nome]) VALUES ('Atendente de Videolocadora')
INSERT INTO Funcaos ([Nome]) VALUES ('Aplicador de Maquiagem')
INSERT INTO Funcaos ([Nome]) VALUES ('Atriz/Ator')
INSERT INTO Funcaos ([Nome]) VALUES ('Auditor')
INSERT INTO Funcaos ([Nome]) VALUES ('Auxiliar de Produção')
INSERT INTO Funcaos ([Nome]) VALUES ('Auxiliar Geral')
INSERT INTO Funcaos ([Nome]) VALUES ('Blitz/Sampling')
INSERT INTO Funcaos ([Nome]) VALUES ('Borrifação')
INSERT INTO Funcaos ([Nome]) VALUES ('Cabeleireiro')
INSERT INTO Funcaos ([Nome]) VALUES ('Coloração de Cabelo')
INSERT INTO Funcaos ([Nome]) VALUES ('Confeitieiro')
INSERT INTO Funcaos ([Nome]) VALUES ('Consultor de Beleza')
INSERT INTO Funcaos ([Nome]) VALUES ('Culinarista')
INSERT INTO Funcaos ([Nome]) VALUES ('Cliente Misterioso')
INSERT INTO Funcaos ([Nome]) VALUES ('Costureira')
INSERT INTO Funcaos ([Nome]) VALUES ('Copeira')
INSERT INTO Funcaos ([Nome]) VALUES ('Degustador')
INSERT INTO Funcaos ([Nome]) VALUES ('Demonstrador')
INSERT INTO Funcaos ([Nome]) VALUES ('Dermoconsultor')
INSERT INTO Funcaos ([Nome]) VALUES ('Digitador')
INSERT INTO Funcaos ([Nome]) VALUES ('Estagiário')
INSERT INTO Funcaos ([Nome]) VALUES ('Esteticista')
INSERT INTO Funcaos ([Nome]) VALUES ('Fatiador de Frios')
INSERT INTO Funcaos ([Nome]) VALUES ('Faxineiro')
INSERT INTO Funcaos ([Nome]) VALUES ('Gerente')
INSERT INTO Funcaos ([Nome]) VALUES ('Garçom')
INSERT INTO Funcaos ([Nome]) VALUES ('Help Desk')
INSERT INTO Funcaos ([Nome]) VALUES ('Impulsionador de Vendas')
INSERT INTO Funcaos ([Nome]) VALUES ('Locutor')
INSERT INTO Funcaos ([Nome]) VALUES ('Merchandising')
INSERT INTO Funcaos ([Nome]) VALUES ('Modelo')
INSERT INTO Funcaos ([Nome]) VALUES ('Monitor')
INSERT INTO Funcaos ([Nome]) VALUES ('Motoqueiro')
INSERT INTO Funcaos ([Nome]) VALUES ('Motorista')
INSERT INTO Funcaos ([Nome]) VALUES ('Operador de Caixa')
INSERT INTO Funcaos ([Nome]) VALUES ('Panfletagem')
INSERT INTO Funcaos ([Nome]) VALUES ('Personal Trainner')
INSERT INTO Funcaos ([Nome]) VALUES ('Psicologia')
INSERT INTO Funcaos ([Nome]) VALUES ('Pesquisador')
INSERT INTO Funcaos ([Nome]) VALUES ('Promotor de Merchandising')
INSERT INTO Funcaos ([Nome]) VALUES ('Promotor de Vendas')
INSERT INTO Funcaos ([Nome]) VALUES ('Propagandista')
INSERT INTO Funcaos ([Nome]) VALUES ('Eventos/Feiras')
INSERT INTO Funcaos ([Nome]) VALUES ('Recreacionista')
INSERT INTO Funcaos ([Nome]) VALUES ('Recrutamento & Seleção')
INSERT INTO Funcaos ([Nome]) VALUES ('Repositor')
INSERT INTO Funcaos ([Nome]) VALUES ('Segurança')
INSERT INTO Funcaos ([Nome]) VALUES ('Supervisor')
INSERT INTO Funcaos ([Nome]) VALUES ('Telefonista')
INSERT INTO Funcaos ([Nome]) VALUES ('Telemarketing Ativo')
INSERT INTO Funcaos ([Nome]) VALUES ('Telemarketing Receptivo')
INSERT INTO Funcaos ([Nome]) VALUES ('Vendedor Externo')
INSERT INTO Funcaos ([Nome]) VALUES ('Vendedor Interno')
INSERT INTO Funcaos ([Nome]) VALUES ('Vitrine Viva')
INSERT INTO Funcaos ([Nome]) VALUES ('Vitrinista')