INSERT INTO Segmentos ([Nome]) VALUES ('Academia')
INSERT INTO Segmentos ([Nome]) VALUES ('Aeroporto')
INSERT INTO Segmentos ([Nome]) VALUES ('Administrativo')
INSERT INTO Segmentos ([Nome]) VALUES ('Agência de viagem')
INSERT INTO Segmentos ([Nome]) VALUES ('Automóveis')
INSERT INTO Segmentos ([Nome]) VALUES ('Alimento para cães')
INSERT INTO Segmentos ([Nome]) VALUES ('Almoxarifado')
INSERT INTO Segmentos ([Nome]) VALUES ('Bazar/Brinquedos')
INSERT INTO Segmentos ([Nome]) VALUES ('Bebidas')
INSERT INTO Segmentos ([Nome]) VALUES ('Beleza Corporal')
INSERT INTO Segmentos ([Nome]) VALUES ('Beleza Facial')
INSERT INTO Segmentos ([Nome]) VALUES ('Buffet')
INSERT INTO Segmentos ([Nome]) VALUES ('Calçados')
INSERT INTO Segmentos ([Nome]) VALUES ('Cartão de Crédito')
INSERT INTO Segmentos ([Nome]) VALUES ('Comercial')
INSERT INTO Segmentos ([Nome]) VALUES ('Comunicação')
INSERT INTO Segmentos ([Nome]) VALUES ('Comunicação Visual')
INSERT INTO Segmentos ([Nome]) VALUES ('Consórcio')
INSERT INTO Segmentos ([Nome]) VALUES ('Consultoria Empresarial')
INSERT INTO Segmentos ([Nome]) VALUES ('Confecções')
INSERT INTO Segmentos ([Nome]) VALUES ('Congelados/Frios/Refrigerados')
INSERT INTO Segmentos ([Nome]) VALUES ('Congressos e Convenções')
INSERT INTO Segmentos ([Nome]) VALUES ('Corretora de Seguros')
INSERT INTO Segmentos ([Nome]) VALUES ('Cosméticos')
INSERT INTO Segmentos ([Nome]) VALUES ('Degustação de vinhos')
INSERT INTO Segmentos ([Nome]) VALUES ('Diretoria')
INSERT INTO Segmentos ([Nome]) VALUES ('Departamento Pessoal')
INSERT INTO Segmentos ([Nome]) VALUES ('Eletro-Eletrônicos (linha branca)')
INSERT INTO Segmentos ([Nome]) VALUES ('Eletro-Eletrônicos (linha marrom)')
INSERT INTO Segmentos ([Nome]) VALUES ('Embalagens')
INSERT INTO Segmentos ([Nome]) VALUES ('Enfermagem')
INSERT INTO Segmentos ([Nome]) VALUES ('Escritório')
INSERT INTO Segmentos ([Nome]) VALUES ('Eventos')
INSERT INTO Segmentos ([Nome]) VALUES ('Eventos automobilísticos')
INSERT INTO Segmentos ([Nome]) VALUES ('Fantasia')
INSERT INTO Segmentos ([Nome]) VALUES ('Financeira')
INSERT INTO Segmentos ([Nome]) VALUES ('Feiras')
INSERT INTO Segmentos ([Nome]) VALUES ('Higiene')
INSERT INTO Segmentos ([Nome]) VALUES ('Higiene bucal')
INSERT INTO Segmentos ([Nome]) VALUES ('Imóveis')
INSERT INTO Segmentos ([Nome]) VALUES ('Informática')
INSERT INTO Segmentos ([Nome]) VALUES ('Internet')
INSERT INTO Segmentos ([Nome]) VALUES ('Joalheria')
INSERT INTO Segmentos ([Nome]) VALUES ('Laticínios')
INSERT INTO Segmentos ([Nome]) VALUES ('Livraria')
INSERT INTO Segmentos ([Nome]) VALUES ('Limpeza')
INSERT INTO Segmentos ([Nome]) VALUES ('Logística')
INSERT INTO Segmentos ([Nome]) VALUES ('Maquiagem')
INSERT INTO Segmentos ([Nome]) VALUES ('Marketing')
INSERT INTO Segmentos ([Nome]) VALUES ('Motorista')
INSERT INTO Segmentos ([Nome]) VALUES ('Móveis')
INSERT INTO Segmentos ([Nome]) VALUES ('Operacional')
INSERT INTO Segmentos ([Nome]) VALUES ('Páscoa')
INSERT INTO Segmentos ([Nome]) VALUES ('Perfumaria')
INSERT INTO Segmentos ([Nome]) VALUES ('Plano de saúde')
INSERT INTO Segmentos ([Nome]) VALUES ('Produção')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Agropecuários')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Alimentícios Perecíveis')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Dietéticos')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Esportivos')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Farmacêuticos')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Infantis')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Naturais')
INSERT INTO Segmentos ([Nome]) VALUES ('Produtos Veterinários')
INSERT INTO Segmentos ([Nome]) VALUES ('Provedores de Internet')
INSERT INTO Segmentos ([Nome]) VALUES ('Porta a porta')
INSERT INTO Segmentos ([Nome]) VALUES ('Refresqueira')
INSERT INTO Segmentos ([Nome]) VALUES ('Saúde')
INSERT INTO Segmentos ([Nome]) VALUES ('Telefonia Celular')
INSERT INTO Segmentos ([Nome]) VALUES ('Telefonia Fixa')
INSERT INTO Segmentos ([Nome]) VALUES ('Têxtil')
INSERT INTO Segmentos ([Nome]) VALUES ('Troca de Cupons')
INSERT INTO Segmentos ([Nome]) VALUES ('Videokê')