INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Curto')
INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Médio')
INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Longo')
INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Afro')
INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Calvo')
INSERT INTO CabeloComprimentos ([Nome]) VALUES ('Careca')

INSERT INTO CabeloCors ([Nome]) VALUES ('Natural')
INSERT INTO CabeloCors ([Nome]) VALUES ('Tingido')
INSERT INTO CabeloCors ([Nome]) VALUES ('Reflexos/Luzes')
INSERT INTO CabeloCors ([Nome]) VALUES ('Manchados')
INSERT INTO CabeloCors ([Nome]) VALUES ('Grisalhos')
INSERT INTO CabeloCors ([Nome]) VALUES ('Quebradiços/Judiados')
INSERT INTO CabeloCors ([Nome]) VALUES ('Californianas')

INSERT INTO CabeloTipos ([Nome]) VALUES ('Liso')
INSERT INTO CabeloTipos ([Nome]) VALUES ('Alisado/Relaxado')
INSERT INTO CabeloTipos ([Nome]) VALUES ('Ondulado')
INSERT INTO CabeloTipos ([Nome]) VALUES ('Crespo')
INSERT INTO CabeloTipos ([Nome]) VALUES ('Cacheado')

INSERT INTO TipoFisicos ([Nome]) VALUES ('Atlético')
INSERT INTO TipoFisicos ([Nome]) VALUES ('Normal')
INSERT INTO TipoFisicos ([Nome]) VALUES ('Magra(o)')
INSERT INTO TipoFisicos ([Nome]) VALUES ('Quadril largo')
INSERT INTO TipoFisicos ([Nome]) VALUES ('Gorda(o)')
INSERT INTO TipoFisicos ([Nome]) VALUES ('Seios avantajados')

INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Perfeitos')
INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Alinhados')
INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Desalinhados')
INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Dentes faltantes')
INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Separados')
INSERT INTO AvaliacaoDentesSorrisos ([Nome]) VALUES ('Proeminentes')

INSERT INTO AvaliacaoDentesCors ([Nome]) VALUES ('Brancos')
INSERT INTO AvaliacaoDentesCors ([Nome]) VALUES ('Amarelos')
INSERT INTO AvaliacaoDentesCors ([Nome]) VALUES ('Cariados')
INSERT INTO AvaliacaoDentesCors ([Nome]) VALUES ('Manchados')
INSERT INTO AvaliacaoDentesCors ([Nome]) VALUES ('Escuros')

INSERT INTO TipoDePeles ([Nome]) VALUES ('Normal')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Manchada')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Sardas')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Rugas')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Acne')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Cicatriz')
INSERT INTO TipoDePeles ([Nome]) VALUES ('Bebe')
INSERT INTO TipoDePeles ([Nome]) VALUES ('MarcasDeExpressao')
INSERT INTO TipoDePeles ([Nome]) VALUES ('MarcasDeEspinha')
INSERT INTO TipoDePeles ([Nome]) VALUES ('OlheirasEscuras')


INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Beleza')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Simpatia')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Falta de Postura')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Antipatia')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Boa Comunicação')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Iniciativa')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Dinamismo')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Ansiedade')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Insegurança')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Timidez')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Apatia')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Boa Educação')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Bom Vocabulário')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Excesso de Gírias')
INSERT INTO PerfilComportalmentals ([Nome]) VALUES ('Erros de Português')

INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Merchandising Cruzado')
INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Wobler')
INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Clip-Strip')
INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Faixa de Gôndola')
INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Construção de Ilhas')
INSERT INTO ConhecimentoMerchandisings ([Nome]) VALUES ('Ponto Extra')

INSERT INTO PerfilProfissionals ([Nome]) VALUES ('GSK Alimentar')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('GSK Farma Júnior')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Loreal Coloração')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Nature Valley')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Loreal Maquiagem')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Serrabela')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Fatiador')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Consultora de Vendas Rituals')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Dermo Nívea')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Canon')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Dermo Jovem Senhora')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Supervisão')
INSERT INTO PerfilProfissionals ([Nome]) VALUES ('Vagas Internas')

INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Disponível')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Doença')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Gravidez')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Contatos Desatualizados')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Funcionário Fixo da Café')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Funcionário Temporário da Café')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Trabalho Fixo')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Trabalho Temporário')
INSERT INTO SituacaoCandidatos ([Nome]) VALUES ('Lista Negra')